#!/bin/bash

function mountChecker() {
    ls $1 > /dev/null 2>&1
    if [ $? = "0" ];
    then
        if [ "$(ls -Al $1 | egrep '^-|d' | wc -l)" -ge 0 ];
        then
            echo -e "\033[0;32m[mounted]\033[0m $1"
        else
            echo -e "\033[1;31m[failed]\033[0m  $1"
        fi
    else
        echo -e "\033[1;31m[failed]\033[0m  $1"
    fi
}

echo "Mount checker:"
mountChecker /home/shared/
echo ""
