#!/bin/bash

function mountChecker() {
    for arg in $@
    do
        ls $arg > /dev/null 2>&1
        if [ $? = "0" ];
        then
            if [ "$(ls -Al $arg | egrep '^-|d' | wc -l)" != '0' ];
            then
                echo -e "\033[0;32m[mounted]\033[0m $arg"
            else
                echo -e "\033[1;33m[empty]\033[0m   $arg"
            fi
        else
            echo -e "\033[1;31m[failed]\033[0m  $arg"
        fi
    done
}

echo "Mount checker:"
mountChecker /home/shared/
echo ""
